var xsll = [{
    score:"",
    type: 2,
    toptitle: "教学态度",
    content: "教材准备充分",
    text: "",
    maxscore: 5,
}, {
    score:"",
    type: 2,
    toptitle: "教学态度",
    content: "教学备课认真",
    text: "",
    maxscore: 5,
}, {
    score:"",
    type: 2,
    toptitle: "教学态度",
    content: "上课时间准备",
    text: "",
    maxscore: 5,
}, {
    score:"",
    type: 2,
    toptitle: "教学态度",
    content: "授课形式丰富（挂图、摸型、幻灯）",
    text: "",
    maxscore: 5,
}, {
    score:"",
    type: 2,
    toptitle: "教学能力",
    content: "口齿清晰准确",
    text: "",
    maxscore: 5,
}, {
    score:"",
    type: 2,
    toptitle: "教学能力",
    content: "语言生动易懂",
    text: "",
    maxscore: 5,
}, {
    score:"",
    type: 2,
    toptitle: "教学能力",
    content: "讲课逻辑性强",
    text: "",
    maxscore: 5,
}, {
    score:"",
    type: 2,
    toptitle: "教学能力",
    content: "板书书写清晰",
    text: "",
    maxscore: 5,
}, {
    score:"",
    type: 2,
    toptitle: "教学水平",
    content: "内容新颖实用",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学水平",
    content: "理论阐述透彻",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学水平",
    content: "知识丰富广博",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学水平",
    content: "重点难点明确	",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学水平",
    content: "归纳总结恰当",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学效果",
    content: "课堂气氛热烈",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学效果",
    content: "师生关系融洽",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学效果",
    content: "内容深浅适宜",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学效果",
    content: "掌握理解全面",
    text: "",
    maxscore: 6,
}, {
    score:"",
    type: 2,
    toptitle: "教学效果",
    content: "总体评价满意",
    text: "",
    maxscore: 6,
}]

var bltl = [{
    score:"",
    type: 4,
    toptitle: "教学准备",
    content: "病例选择适当，提前印发病历摘要、书写发言提纲，提出能引导学生参与讨论的问题。",
    text: "",
    maxscore: 15,
}, {
    score:"",
    type: 4,
    toptitle: "计划目标",
    content: "重视基础理论、基本知识培养，体现出对教学内容的掌握、熟悉、了解的不同要求，教学设计合理，教学目标明确。",
    text: "",
    maxscore: 15,
}, {
    score:"",
    type: 4,
    toptitle: "临床分析",
    content: "结合病例综合分析收集的资料、引导学生正确诊断和鉴别诊断或制定治疗计划，培养临床思维能力。",
    text: "",
    maxscore: 25,
}, {
    score:"",
    type: 4,
    toptitle: "启发教学",
    content: "病例讨论时，互动式教学运用得当。主持人按照预先的教学设计，在讨论中积极引导学生发言和正确思维，教学效果好。",
    text: "",
    maxscore: 15,
}, {
    score:"",
    type: 4,
    toptitle: "归纳总结",
    content: "归纳总结讨论内容重点突出，学生收获大。",
    text: "",
    maxscore: 20,
}, {
    score:"",
    type: 4,
    toptitle: "为人师表",
    content: "讨论中条理清楚，谈吐文雅，着装整洁大方，注重普通话教学。",
    text: "",
    maxscore: 10,
}]

var jxcf = [{
    score:"",
    type: 3,
    toptitle: "教学准备",
    content: "师生均熟悉患者病情，全面掌握近期演变情况",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "计划目标",
    content: "重视基本理论、基础知识、基本技能培养，对教学内容的掌握、熟练、了解三级要求层次分明",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "查房主持",
    content: "教学查房由副主任医以上教师担任，查房过程中能体现“三级查房”。",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "病例选择",
    content: "精心选择有一定典型性、或便于对某一症候群进行鉴别分析的病例",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "查体指导",
    content: "查体示范指导规范、标准",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "临床分析",
    content: "能结合病例综合分析收集的资料，正确诊断，制定治疗计划",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "启发教学",
    content: "善于诱导学生的临床思维兴趣，耐心解答各种问题，及时纠正学生的不足",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "归纳总结",
    content: "引导学生归纳总结学习内容和收获",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "为人师表",
    content: "礼貌待人，体恤病人，着装大方，谈吐文雅",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 3,
    toptitle: "教学查房过程	",
    content: "符合教学查房的基本要求",
    text: "",
    maxscore: 10,
}]

var xjk = [{
    score:"",
    type: 1,
    toptitle: "",
    content: "备课认真，准备充分	",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "上课准时，仪表端庄	",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "授课形式丰富(挂图、模型、幻灯、)	",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "结合临床，生动易懂 ",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "条理清晰，重点突出	",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "知识广博，逻辑性强	",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "阐述透彻，启发思维	",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "内容详尽，深浅适宜	",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "把握动态，推介三新	",
    text: "",
    maxscore: 10,
}, {
    score:"",
    type: 1,
    toptitle: "",
    content: "课堂气氛热烈、融洽	",
    text: "",
    maxscore: 10,
}]
